### ISSUE TITLE
Consider methods for hosting the front-end SPA and the server

### ISSUE THREAD

**Issue by trabianmatt** [DeathstarNovember/competition#1]
The repo as-is currently has the following structure:

```
- assets
- config
- lib
- ...other server-related dirs
- web (SPA dir)
```

The `web` directory and the server directories are at the same level.

### Here are two options for us to consider:

1. Completely split the backend and frontend:

```
- server
  - assets (perhaps not needed in this model?)
  - config
  - lib
  - ... etc.
- web (SPA)
```

2. Move the SPA to the `assets` directory and deploy the React app within the Phoenix context. We could [still use Create React App](http://www.petecorey.com/blog/2017/04/03/using-create-react-app-with-phoenix/?from=east5th.co).

I lean towards #1 with the `assets` directory completely removed, but I'm open to either.

**Comment by felixakiragreen** [comment]
I think the simplest would be (#2) - moving the SPA to `/assets` and deploy it from there. I have successfully deployed elixir apps, and it's even easier now with [elixir 1.9](https://elixir-lang.org/blog/2019/06/24/elixir-v1-9-0-released/). That way it can all be hosted and managed in a single instance. 

The only downside if  you make any changes to only the backend or frontend, you need to update everything.

**Comment by DeathstarNovember** [comment]
Ok, so... I split the front and back end in to 2 repos and 2 Heroku apps that just talk to each other over the internet. There are still a few environment things to work out, but the app is up and live at https://competitor-prod.herokuapp.com/
